version: "3"
services:
  app:
    container_name: theatre-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    env_file:
       - .env
    depends_on:
      - db
    volumes:
      - ./:/app
      - static_data:/vol/web/static
      - media_data:/vol/web/media

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  static_data:
  media_data:
  postgres_data:
